services:
  - type: web
    name: startup-accelerator-websocket
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: JWT_PASSWORD
        generateValue: true
      - key: FRONTEND_URL
        value: https://startup-accelerator-k3woo186-dassoham345-gmailcoms-projects.vercel.app
