services:
  - type: web
    name: startup-accelerator-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
      - key: JWT_PASSWORD
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://startup-accelerator-backend.onrender.com/api/v1/auth/google/callback
      - key: FRONTEND_URL
        value: https://your-app.vercel.app
      - key: GEMINI_API_KEY
        sync: false
