[build]
  base = "metaverse/apps/frontend"
  publish = "metaverse/apps/frontend/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# Environment variables for production
[context.production.environment]
  VITE_USE_MOCK_API = "true"
  VITE_API_URL = "https://your-api.railway.app"
  VITE_SOCKET_URL = "https://your-websocket.railway.app"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  VITE_USE_MOCK_API = "true"
