[build]
  base = "metaverse/apps/frontend"
  publish = "metaverse/apps/frontend/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
